#!/usr/bin/env python3
"""
embed_assets.py  —  MyEngine asset embedder
============================================
Converts every file in assets/ into a C++ byte array.
Run automatically by CMake before building.

Usage:
    python3 embed_assets.py <assets_dir> <output_cpp> <output_h>

Example:
    python3 tools/embed_assets.py assets src/EmbeddedAssets.cpp src/EmbeddedAssets.h
"""

import sys
import os
import re
from pathlib import Path

def make_identifier(path: str) -> str:
    """Convert a file path to a valid C identifier.
    'assets/models/phone.obj'  ->  'assets_models_phone_obj'
    """
    # Normalize separators, strip leading assets/
    s = path.replace("\\", "/")
    s = re.sub(r"[^a-zA-Z0-9]", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s

def embed(assets_dir: str, out_cpp: str, out_h: str):
    assets_dir = Path(assets_dir)
    if not assets_dir.exists():
        print(f"[embed] assets dir not found: {assets_dir} — skipping")
        # Write empty stubs so the build doesn't break
        Path(out_h).write_text(
            "#pragma once\n#include \"res/EmbeddedRegistry.h\"\n"
            "inline void registerEmbeddedAssets() {}\n")
        Path(out_cpp).write_text(
            "#include \"EmbeddedAssets.h\"\n")
        return

    # Gather all files recursively
    files = sorted(f for f in assets_dir.rglob("*") if f.is_file())

    # ── Write header ─────────────────────────────────────────────────────────
    h_lines = [
        "// AUTO-GENERATED by tools/embed_assets.py — DO NOT EDIT",
        "#pragma once",
        '#include "res/EmbeddedRegistry.h"',
        "",
        "// Forward declarations of embedded data arrays",
    ]

    for f in files:
        rel   = f.relative_to(assets_dir.parent)   # e.g. assets/models/phone.obj
        ident = make_identifier(str(rel))
        size  = f.stat().st_size
        h_lines.append(f"extern const unsigned char {ident}[{size}];")
        h_lines.append(f"extern const unsigned int  {ident}_size;  // {size} bytes")

    h_lines += [
        "",
        "// Call once at startup (before any resource loads)",
        "void registerEmbeddedAssets();",
    ]

    Path(out_h).parent.mkdir(parents=True, exist_ok=True)
    Path(out_h).write_text("\n".join(h_lines) + "\n", encoding="utf-8")
    print(f"[embed] wrote {out_h}")

    # ── Write cpp ─────────────────────────────────────────────────────────────
    cpp_lines = [
        "// AUTO-GENERATED by tools/embed_assets.py — DO NOT EDIT",
        f'#include "{Path(out_h).name}"',
        '#include "res/EmbeddedRegistry.h"',
        "",
    ]

    entry_calls = []

    for f in files:
        rel   = f.relative_to(assets_dir.parent)   # assets/textures/wall.png
        ident = make_identifier(str(rel))
        key   = str(rel).replace("\\", "/")         # virtual path key
        data  = f.read_bytes()
        size  = len(data)

        # Emit array in chunks of 16 bytes per line
        cpp_lines.append(f"// {key}  ({size} bytes)")
        cpp_lines.append(f"const unsigned int {ident}_size = {size}u;")
        cpp_lines.append(f"const unsigned char {ident}[{size}] = {{")

        chunks = [data[i:i+16] for i in range(0, len(data), 16)]
        for chunk in chunks:
            hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
            cpp_lines.append(f"    {hex_vals},")

        cpp_lines += ["};", ""]

        # Registration call
        entry_calls.append(
            f'    EmbeddedRegistry::get().add("{key}", {ident}, {ident}_size);')

    cpp_lines += [
        "void registerEmbeddedAssets() {",
        "    auto& reg = EmbeddedRegistry::get();",
        "    (void)reg;",
    ] + entry_calls + [
        "}",
        "",
    ]

    Path(out_cpp).parent.mkdir(parents=True, exist_ok=True)
    Path(out_cpp).write_text("\n".join(cpp_lines) + "\n", encoding="utf-8")

    total_kb = sum(f.stat().st_size for f in files) / 1024
    print(f"[embed] wrote {out_cpp}  ({len(files)} files, {total_kb:.1f} KB total)")

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: embed_assets.py <assets_dir> <output.cpp> <output.h>")
        sys.exit(1)
    embed(sys.argv[1], sys.argv[2], sys.argv[3])
