// AUTO-GENERATED by tools/embed_assets.py — DO NOT EDIT
#pragma once
#include "res/EmbeddedRegistry.h"

// Forward declarations of embedded data arrays
extern const unsigned char assets_sound_sound_wav[173162];
extern const unsigned int  assets_sound_sound_wav_size;  // 173162 bytes

// Call once at startup (before any resource loads)
void registerEmbeddedAssets();
