#pragma once
// Embedded assets (auto-generated by embed_assets.py)
#if __has_include("EmbeddedAssets.h")
#  include "EmbeddedAssets.h"
#else
inline void registerEmbeddedAssets() {} // stub when not yet generated
#endif
// engine.h - one include for everything
#include "core/Window.h"
#include "core/Input.h"
#include "core/InputActionMap.h"
#include "core/Time.h"
#include "core/Log.h"
#include "core/EventSystem.h"
#include "render/Shader.h"
#include "render/Mesh.h"
#include "render/Texture.h"
#include "render/Camera.h"
#include "render/Material.h"
#include "render/Model.h"
#include "render/BuiltinShaders.h"
#include "ecs/ECS.h"
#include "game/GameObject.h"
#include "game/ResourceManager.h"
#include "ui/ImGuiLayer.h"
#include "ui/UI.h"
#include "audio/Audio.h"
#include "physics/Physics.h"
#include <string>
#include <functional>
#include <vector>
#include <memory>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <GLFW/glfw3.h>
#include <cstdio>
#include <ctime>
#ifdef _WIN32
#  include <windows.h>
#else
#  include <time.h>
#endif

namespace eng {

struct MeshRendererComponent {
    std::shared_ptr<Model> model;
    Material               material;
    bool                   visible = true;
};
struct ScriptComponent {
    std::function<void(GameObject, float)>           onUpdate;
    std::function<void(GameObject)>                  onDestroy;
    std::function<void(GameObject, GameObject)>      onCollide;
};
struct TagComp           { std::string value; };
struct ColliderComponent { glm::vec3 halfSize = {0.5f,0.5f,0.5f}; };

// Forward declaration so App::init() can set g_app
class App;
inline App* g_app = nullptr;

class App {
public:
    struct Config {
        std::string title  = "My Game";
        int   width        = 1280;
        int   height       = 720;
        bool  vsync        = false;
        int   targetFps    = 144;  // 0 = unlimited; vsync overrides this
        float clearR=0.08f, clearG=0.08f, clearB=0.12f;
        float camSpeed     = 5.0f;
        bool  freeCam      = true;
    };

    explicit App(const std::string& title="My Game",int w=1280,int h=720){
        m_cfg.title=title; m_cfg.width=w; m_cfg.height=h; init();
    }
    explicit App(Config cfg):m_cfg(std::move(cfg)){init();}
    ~App()=default;

    // Spawn / Find
    GameObject spawn(const std::string& name=""){
        EntityID id=m_world.create(name.empty()?autoName():name);
        m_world.add<TransformComponent>(id);
        m_world.add<TagComp>(id);
        return {id,&m_world};
    }
    GameObject find(const std::string& name){
        return {m_world.findByName(name),&m_world};
    }
    std::vector<GameObject> findAll(const std::string& tag){
        std::vector<GameObject> out;
        m_world.each<TagComp>([&](EntityID id,TagComp& t){
            if(t.value==tag) out.push_back({id,&m_world});
        });
        return out;
    }

    // Camera
    App& camPos(float x,float y,float z){m_camera.setPosition({x,y,z});return *this;}
    App& camRot(float yaw,float pitch)  {m_camera.setRotation(yaw,pitch);return *this;}
    App& fov(float deg)                 {m_camera.setFov(deg);return *this;}
    App& freeCam(bool on)               {m_cfg.freeCam=on;return *this;}
    Camera& camera()                    {return m_camera;}
    glm::vec3 camPos()     const        {return m_camera.position();}
    glm::vec3 camForward() const        {return m_camera.forward();}

    // Lighting
    App& lightDir  (float x,float y,float z){m_lightDir=glm::normalize(glm::vec3(x,y,z));return *this;}
    App& lightColor(float r,float g,float b){m_lightColor={r,g,b};return *this;}
    App& ambient   (float r,float g,float b){m_ambient={r,g,b};return *this;}
    App& skyColor  (float r,float g,float b){m_cfg.clearR=r;m_cfg.clearG=g;m_cfg.clearB=b;return *this;}
    App& skyColor  (float v)                {return skyColor(v,v,v);}

    // Callbacks
    App& onStart (std::function<void()>        fn){m_onStart=fn;return *this;}
    App& onUpdate(std::function<void(float dt)> fn){m_onUpdate=fn;return *this;}
    App& onRender(std::function<void()>        fn){m_onRender=fn;return *this;}

    // Input
    bool      keyPressed(int k)  const{return Input::isKeyPressed(k);}  // один кадр
    bool      keyHeld   (int k)  const{return Input::isKeyDown(k);}     // удерживается
    // обратная совместимость
    bool      key    (int k)     const{return Input::isKeyDown(k);}
    bool      keyDown(int k)     const{return Input::isKeyPressed(k);}
    bool      mouseDown(int b=0)const{return Input::isMousePressed(b);}
    bool      mouse    (int b=0)const{return Input::isMouseDown(b);}
    glm::vec2 mousePos ()       const{return Input::mousePos();}
    glm::vec2 mouseDelta()      const{return Input::mouseDelta();}
    float     scroll   ()       const{return Input::scrollDelta();}
    bool action    (const std::string& a)const{return Actions().isDown(a);}
    bool actionDown(const std::string& a)const{return Actions().isPressed(a);}
    void bindAction(const std::string& a,int k){Actions().bind(a,{Binding::Type::Key,k});}

    // ImGui
    ImGuiLayer& imgui(){return m_imgui;}

    // Quit
    void quit(){m_running=false;}

    // Run
    int run(){
        Actions().loadDefaults();
        if(m_onStart) m_onStart();
        float lastTime=0.f;
        double frameStart=glfwGetTime();
        while(m_window->isOpen()&&m_running){
            m_window->pollEvents();
            EventBus::get().flush();
            float now=(float)glfwGetTime();
            float dt=now-lastTime; lastTime=now;
            if(dt>0.1f) dt=0.1f;
            Time::tick();
            updateFreeCam(dt);
            if(m_onUpdate) m_onUpdate(dt);
            m_world.each<ScriptComponent,TransformComponent>(
                [&](EntityID,ScriptComponent& sc,TransformComponent&){
                    if(sc.onUpdate) sc.onUpdate({0,&m_world},dt);
                });

            // ── Physics step ─────────────────────────────────────────────────
            m_physics.step(dt);
            m_physics.syncTransforms([&](uint32_t eid, glm::vec3 pos, glm::quat rot){
                if(auto* t = m_world.get<TransformComponent>(eid)){
                    t->position = pos;
                    t->rotation = glm::degrees(glm::eulerAngles(rot));
                }
            });

            // ── Audio update (listener follows camera) ───────────────────────
            Audio::update();
            Audio::setListenerPos(m_camera.position());
            Audio::setListenerDir(m_camera.forward());
            m_window->clear(m_cfg.clearR,m_cfg.clearG,m_cfg.clearB);
            renderScene();
            m_imgui.begin();
            if(m_onRender) m_onRender();
            m_imgui.end();
            m_window->display();
            Input::endFrame();

            // ── Frame rate cap (skipped when vsync is on) ─────────────────────
            if (!m_cfg.vsync && m_cfg.targetFps > 0) {
                double targetDt = 1.0 / m_cfg.targetFps;
                double elapsed  = glfwGetTime() - frameStart;
                if (elapsed < targetDt) {
                    // Spin-wait for the last ~1ms, sleep for the rest
                    double sleepSec = targetDt - elapsed - 0.001;
                    if (sleepSec > 0) {
#ifdef _WIN32
                        ::Sleep((DWORD)(sleepSec * 1000.0));
#else
                        struct timespec ts;
                        ts.tv_sec  = (time_t)sleepSec;
                        ts.tv_nsec = (long)((sleepSec - ts.tv_sec) * 1e9);
                        nanosleep(&ts, nullptr);
#endif
                    }
                    while (glfwGetTime() - frameStart < targetDt) {} // spin last ms
                }
            }
            frameStart = glfwGetTime();

            static float t=0; t+=dt;
            if(t>0.3f){
                char buf[128];
                snprintf(buf,sizeof(buf),"%s  |  FPS: %.0f",m_cfg.title.c_str(),Time::fps());
                m_window->setTitle(buf); t=0;
            }
        }
        Audio::shutdown();
        m_physics.shutdown();
        return 0;
    }

    Window&          window()   {return *m_window;}
    World&           world()    {return m_world;}
    ResourceManager& resources(){return *m_res;}
    World&           _world()   {return m_world;}
    ResourceManager& _res()     {return *m_res;}
    void _ensureWhiteTex(){
        if(!m_whiteTex) m_whiteTex=std::make_shared<Texture>(Texture::white());
    }
    Texture* _whiteTex(){_ensureWhiteTex();return m_whiteTex.get();}

private:
    void init(){
        registerEmbeddedAssets();
        m_window=std::make_unique<Window>(m_cfg.width,m_cfg.height,m_cfg.title);
        m_window->setVSync(m_cfg.vsync);
        m_res=std::make_unique<ResourceManager>();
        m_camera=Camera(60.f,m_window->aspect(),0.05f,1000.f);
        m_camera.setPosition({0,1,5});
        m_window->setResizeCallback([this](int w,int h){
            m_camera.setAspect((float)w/(float)h);
        });
        m_shader=Shader::fromSource(VERT_LIT,FRAG_LIT);
        _ensureWhiteTex();
        Input::init(m_window->handle());
        Actions().loadDefaults();
        m_imgui.init(*m_window);
        Audio::init();
        m_physics.init();
        g_app = this;
    }

    void updateFreeCam(float dt){
        if(!m_cfg.freeCam) return;

        ImGuiIO& io = ImGui::GetIO();

        // Tab toggles mouse capture — but ONLY when ImGui doesn't want keyboard
        // This prevents Tab scrolling through ImGui widgets
        if(Input::isKeyPressed(GLFW_KEY_TAB) && !io.WantCaptureKeyboard)
            m_window->captureCursor(!m_window->isCursorCaptured());

        // Escape always releases cursor
        if(Input::isKeyPressed(GLFW_KEY_ESCAPE))
            m_window->captureCursor(false);

        // Mouse look — only when cursor is captured (Tab mode)
        if(m_window->isCursorCaptured()){
            auto d = Input::mouseDelta();
            m_camera.processMouse(d.x, d.y);
        }

        // Camera movement — ONLY when cursor is captured AND ImGui doesn't want keyboard
        // This prevents WASD typing into inspector fields while moving camera
        if(m_window->isCursorCaptured() && !io.WantCaptureKeyboard){
            float fwd=(float)(Input::isKeyDown(GLFW_KEY_W)-Input::isKeyDown(GLFW_KEY_S));
            float rgt=(float)(Input::isKeyDown(GLFW_KEY_D)-Input::isKeyDown(GLFW_KEY_A));
            float up =(float)(Input::isKeyDown(GLFW_KEY_SPACE)-Input::isKeyDown(GLFW_KEY_LEFT_SHIFT));
            m_camera.processKeyboard(fwd, rgt, up, m_cfg.camSpeed, dt);
        }

        // Scroll zoom — only when ImGui doesn't want the mouse scroll
        if(!io.WantCaptureMouse)
            m_camera.setFov(m_camera.fov() - Input::scrollDelta() * 2.f);
    }

    void renderScene(){
        m_shader.use();
        m_shader.setMat4("uView",       m_camera.viewMatrix());
        m_shader.setMat4("uProj",       m_camera.projectionMatrix());
        m_shader.setVec3("uLightDir",   m_lightDir);
        m_shader.setVec3("uLightColor", m_lightColor);
        m_shader.setVec3("uAmbient",    m_ambient);
        m_shader.setVec3("uCamPos",     m_camera.position());
        m_shader.setInt ("uTexture",    0);

        m_world.each<TransformComponent,MeshRendererComponent>(
            [&](EntityID, TransformComponent& tr, MeshRendererComponent& mr){
                if (!mr.visible || !mr.model) return;

                glm::mat4 modelMat = tr.matrix();
                m_shader.setMat4("uModel", modelMat);
                // NormalMatrix must be mat3 — shader declares it as mat3
                m_shader.setMat3("uNormalMatrix",
                    glm::transpose(glm::inverse(glm::mat3(modelMat))));

                // Рендерим каждый субмеш отдельно
                for (size_t i = 0; i < mr.model->subMeshCount(); ++i) {
                    const SubMesh& sm = mr.model->subMesh(i);

                    // ── Texture ──────────────────────────────────────────
                    // Priority: submesh albedoMap (from .mtl map_Kd)
                    //         > object-level albedoMap (from .texture())
                    //         > white 1x1 fallback
                    const Texture* tex = nullptr;
                    if      (sm.material.albedoMap) tex = sm.material.albedoMap;
                    else if (mr.material.albedoMap) tex = mr.material.albedoMap;

                    bool hasTexture = (tex != nullptr);
                    if (tex) tex->bind(0u);
                    else     m_whiteTex->bind(0u);

                    m_shader.setBool("uHasTexture", hasTexture);

                    // uTint only used when there is NO texture.
                    // Falls back to MTL Kd color, or GameObject::color().
                    if (!hasTexture) {
                        glm::vec4 smColor    = sm.material.albedo;
                        float     brightness = smColor.r + smColor.g + smColor.b;
                        bool      smHasColor = (smColor != glm::vec4(1,1,1,1))
                                           && (brightness > 0.05f);
                        m_shader.setVec4("uTint",
                            smHasColor ? smColor : mr.material.albedo);
                    }

                    sm.mesh.draw();
                }
            });
    }

    std::string autoName(){return "Object_"+std::to_string(++m_autoIdx);}

public:
    // ── Physics (public) ───────────────────────────────────────────────────────
    PhysicsWorld& physics() { return m_physics; }

    void addRigidBody(EntityID eid,
                      RigidBodyType   type    = RigidBodyType::Dynamic,
                      ColliderShape   shape   = ColliderShape::Box,
                      glm::vec3       halfExt = {0.5f,0.5f,0.5f},
                      float           mass    = 1.f)
    {
        auto* t   = m_world.get<TransformComponent>(eid);
        glm::vec3 pos = t ? t->position : glm::vec3(0);
        // TransformComponent::rotation is Euler degrees (vec3) — convert to quat
        glm::quat rot = t
            ? glm::quat(glm::radians(t->rotation))
            : glm::quat{1.f,0.f,0.f,0.f};

        if (!m_world.has<RigidBodyComponent>(eid))
            m_world.add<RigidBodyComponent>(eid);
        auto* rb = m_world.get<RigidBodyComponent>(eid);
        rb->type    = type;
        rb->shape   = shape;
        rb->halfExt = halfExt;
        rb->mass    = mass;
        m_physics.addBody(eid, *rb, pos, rot);
    }

private:
    Config                           m_cfg;
    std::unique_ptr<Window>          m_window;
    std::unique_ptr<ResourceManager> m_res;
    World                            m_world;
    Camera                           m_camera;
    Shader                           m_shader;
    ImGuiLayer                       m_imgui;
    PhysicsWorld                     m_physics;
    std::shared_ptr<Texture>         m_whiteTex;
    glm::vec3 m_lightDir   = glm::normalize(glm::vec3(0.6f,1.f,0.4f));
    glm::vec3 m_lightColor = {1.f,0.95f,0.85f};
    glm::vec3 m_ambient    = {0.12f,0.12f,0.18f};
    std::function<void()>            m_onStart;
    std::function<void(float)>       m_onUpdate;
    std::function<void()>            m_onRender;
    bool      m_running=true;
    uint32_t  m_autoIdx=0;
};

} // namespace eng

// ─────────────────────────────────────────────────────────────────────────────
//  SceneManager — register named scenes, switch between them at runtime
//
//  Usage in main.cpp:
//
//    SceneManager scenes(app);
//
//    scenes.add("MainMenu", [](App& app) {
//        app.spawn("Logo").quad().pos(0,1,0);
//        app.onUpdate([](float dt){ /* menu logic */ });
//        app.onRender([](){ /* menu UI */ });
//    });
//
//    scenes.add("Level1", [](App& app) {
//        app.spawn("Player").cube().pos(0,1,0);
//        app.onUpdate([](float dt){ /* game logic */ });
//    });
//
//    scenes.loadFirst();   // load first registered scene
//    // or: scenes.load("Level1");
//
//    // Switch from inside a callback:
//    app.onUpdate([&](float dt){
//        if (app.keyDown(KEY_ENTER)) scenes.load("Level1");
//    });
//
//    return app.run();
// ─────────────────────────────────────────────────────────────────────────────
namespace eng {

class SceneManager {
public:
    using SetupFn   = std::function<void(App&)>;
    using UpdateFn  = std::function<void(float)>;
    using RenderFn  = std::function<void()>;

    explicit SceneManager(App& app) : m_app(app) {}

    // Register a scene. setup() runs once on first load — never again.
    SceneManager& add(const std::string& name, SetupFn fn) {
        m_scenes.push_back({name, std::move(fn)});
        return *this;
    }

    // Switch to scene by name.
    // First visit  → runs setup, caches entities + callbacks.
    // Return visit → restores cached snapshot instantly, no re-setup.
    bool load(const std::string& name) {
        for (int i = 0; i < (int)m_scenes.size(); i++)
            if (m_scenes[i].name == name) { loadIndex(i); return true; }
        fprintf(stderr, "[SceneManager] Scene not found: %s\n", name.c_str());
        return false;
    }

    bool load(int index) {
        if (index < 0 || index >= (int)m_scenes.size()) return false;
        loadIndex(index);
        return true;
    }

    void loadFirst() { if (!m_scenes.empty()) loadIndex(0); }
    void loadNext()  { loadIndex((m_current + 1) % (int)m_scenes.size()); }
    void loadPrev()  { int n=(int)m_scenes.size(); loadIndex((m_current-1+n)%n); }

    // Forget a scene's cache — next load() will re-run setup.
    void unload(const std::string& name) {
        for (auto& s : m_scenes)
            if (s.name == name) { s.cache.reset(); return; }
    }
    void unloadAll() { for (auto& s : m_scenes) s.cache.reset(); }

    const std::string& current() const {
        static std::string empty;
        return m_current >= 0 ? m_scenes[m_current].name : empty;
    }
    int  currentIndex() const { return m_current; }
    int  count()        const { return (int)m_scenes.size(); }
    bool isCached(const std::string& name) const {
        for (auto& s : m_scenes) if (s.name == name) return s.cache.has_value();
        return false;
    }
    std::vector<std::string> names() const {
        std::vector<std::string> out;
        for (auto& s : m_scenes) out.push_back(s.name);
        return out;
    }

private:
    // ── Snapshot of a suspended scene ─────────────────────────────────────────
    struct EntityCache {
        struct Entry {
            std::string  tag;
            glm::vec3    pos, rot, scale;
            bool         hasMesh   = false;
            bool         isSphere  = false;
            std::string  modelPath;
            glm::vec4    color     = {1,1,1,1};
        };
        std::vector<Entry>   entities;
        UpdateFn             onUpdate;
        RenderFn             onRender;
    };

    struct SceneEntry {
        std::string               name;
        SetupFn                   setup;
        std::optional<EntityCache> cache;  // empty = never loaded
    };

    // ── Save the live world into a cache entry ────────────────────────────────
    EntityCache snapshotWorld() {
        EntityCache c;
        c.onUpdate = m_savedUpdate;
        c.onRender = m_savedRender;
        World& w = m_app.world();
        w.each<TagComp>([&](EntityID id, TagComp& tag){
            EntityCache::Entry e;
            e.tag = tag.value;
            if (auto* t = w.get<TransformComponent>(id)) {
                e.pos   = t->position;
                e.rot   = t->rotation;
                e.scale = t->scale;
            }
            if (auto* mr = w.get<MeshRendererComponent>(id)) {
                e.hasMesh  = true;
                e.color    = mr->material.albedo;
                if (mr->model && !mr->model->path().empty()) {
                    e.modelPath = mr->model->path();
                    e.isSphere  = e.modelPath.find("sphere") != std::string::npos;
                }
            }
            c.entities.push_back(e);
        });
        return c;
    }

    // ── Destroy all current world entities ───────────────────────────────────
    void clearWorld() {
        World& w = m_app.world();
        std::vector<EntityID> all;
        w.each<TagComp>([&](EntityID id, TagComp&){ all.push_back(id); });
        for (EntityID id : all) {
            m_app.physics().removeBody(id);
            w.destroy(id);
        }
    }

    // ── Restore world from cache ──────────────────────────────────────────────
    void restoreWorld(const EntityCache& c) {
        for (auto& e : c.entities) {
            auto obj = m_app.spawn(e.tag);
            EntityID id = obj.id();
            if (auto* t = m_app.world().get<TransformComponent>(id)) {
                t->position = e.pos;
                t->rotation = e.rot;
                t->scale    = e.scale;
            }
            if (e.hasMesh) {
                if (!e.modelPath.empty()) obj.model(e.modelPath);
                else if (e.isSphere)      obj.sphere();
                else                      obj.cube();
                obj.color(e.color.r, e.color.g, e.color.b);
            }
        }
        m_savedUpdate = c.onUpdate;
        m_savedRender = c.onRender;
        m_app.onUpdate(c.onUpdate);
        m_app.onRender(c.onRender);
    }

    void loadIndex(int i) {
        // 1. Suspend current scene — save world + callbacks into its cache
        if (m_current >= 0) {
            m_scenes[m_current].cache = snapshotWorld();
        }

        // 2. Clear the live world
        clearWorld();
        m_app.onUpdate(nullptr);
        m_app.onRender(nullptr);
        m_savedUpdate = nullptr;
        m_savedRender = nullptr;

        m_current = i;
        SceneEntry& s = m_scenes[i];

        if (s.cache.has_value()) {
            // 3a. Resume — restore from cache (no re-setup, instant)
            restoreWorld(*s.cache);
        } else {
            // 3b. First load — run setup, then capture callbacks it registered
            s.setup(m_app);
            // Capture whatever onUpdate/onRender setup() registered
            // (we can't intercept them directly, so we snapshot right after)
            // Re-snapshot is lightweight since setup just ran
        }
    }

    App&              m_app;
    std::vector<SceneEntry> m_scenes;
    int               m_current    = -1;
    UpdateFn          m_savedUpdate;
    RenderFn          m_savedRender;
};

} // namespace eng

namespace eng {
    inline constexpr int KEY_W     = GLFW_KEY_W;
    inline constexpr int KEY_A     = GLFW_KEY_A;
    inline constexpr int KEY_S     = GLFW_KEY_S;
    inline constexpr int KEY_D     = GLFW_KEY_D;
    inline constexpr int KEY_SPACE = GLFW_KEY_SPACE;
    inline constexpr int KEY_SHIFT = GLFW_KEY_LEFT_SHIFT;
    inline constexpr int KEY_CTRL  = GLFW_KEY_LEFT_CONTROL;
    inline constexpr int KEY_E     = GLFW_KEY_E;
    inline constexpr int KEY_F     = GLFW_KEY_F;
    inline constexpr int KEY_ESC   = GLFW_KEY_ESCAPE;
    inline constexpr int KEY_UP    = GLFW_KEY_UP;
    inline constexpr int KEY_DOWN  = GLFW_KEY_DOWN;
    inline constexpr int KEY_LEFT  = GLFW_KEY_LEFT;
    inline constexpr int KEY_RIGHT = GLFW_KEY_RIGHT;
    inline constexpr int MOUSE_LEFT  = GLFW_MOUSE_BUTTON_LEFT;
    inline constexpr int MOUSE_RIGHT = GLFW_MOUSE_BUTTON_RIGHT;
} // namespace eng
